<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Очистить значение',
    'Close the picker' => 'Закрыть календарь',
    'Decrement Hour' => 'Уменьшить час',
    'Decrement Minute' => 'Уменьшить минуты',
    'Decrement Second' => 'Уменьшить секунды',
    'Go to today' => 'Перейти к сегодняшней дате',
    'Increment Hour' => 'Увеличить час',
    'Increment Minute' => 'Увеличить минуты',
    'Increment Second' => 'Увеличить секунды',
    'Next Century' => 'Следующее столетие',
    'Next Decade' => 'Следующая декада',
    'Next Month' => 'Следующий месяц',
    'Next Year' => 'Следующий год',
    'Pick Hour' => 'Выбрать час',
    'Pick Minute' => 'Выбрать минуты',
    'Pick Second' => 'Выбрать секунды',
    'Previous Century' => 'Предыдущее столетие',
    'Previous Decade' => 'Предыдущая декада',
    'Previous Month' => 'Предыдущий месяц',
    'Previous Year' => 'Предыдущий год',
    'Select Decade' => 'Выбрать декаду',
    'Select Month' => 'Выбрать месяц',
    'Select Time' => 'Задать время',
    'Select Year' => 'Выбрать год',
    'Toggle Period' => 'Переключить интервал',
];
