<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Maak selectie leeg',
    'Close the picker' => 'Sluit datumkiezer',
    'Decrement Hour' => 'Uur terug',
    'Decrement Minute' => 'Minuut terug',
    'Decrement Second' => 'Seconde terug',
    'Go to today' => 'Selecteer vandaag',
    'Increment Hour' => 'Uur vooruit',
    'Increment Minute' => 'Minuut vooruit',
    'Increment Second' => 'seconde vooruit',
    'Next Century' => 'Volgende eeuw',
    'Next Decade' => 'Volgend decennium',
    'Next Month' => 'Volgende maand',
    'Next Year' => 'Volgend jaar',
    'Pick Hour' => 'Kies uur',
    'Pick Minute' => 'Kies minuut',
    'Pick Second' => 'Mies seconde',
    'Previous Century' => 'Vorige eeuw',
    'Previous Decade' => 'Vorig decennium',
    'Previous Month' => 'Vorige maand',
    'Previous Year' => 'Vorig jaar',
    'Select Decade' => 'Selecteer decennium',
    'Select Month' => 'Selecteer maand',
    'Select Time' => 'Selecteer tijd',
    'Select Year' => 'Selecteer jaar',
    'Toggle Period' => 'Wissel periode',
];
