<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => '',
    'Close the picker' => '',
    'Decrement Hour' => '',
    'Decrement Minute' => '',
    'Decrement Second' => '',
    'Go to today' => '',
    'Increment Hour' => '',
    'Increment Minute' => '',
    'Increment Second' => '',
    'Next Century' => '',
    'Next Decade' => '',
    'Next Month' => '',
    'Next Year' => '',
    'Pick Hour' => '',
    'Pick Minute' => '',
    'Pick Second' => '',
    'Previous Century' => '',
    'Previous Decade' => '',
    'Previous Month' => '',
    'Previous Year' => '',
    'Select Decade' => '',
    'Select Month' => '',
    'Select Time' => '',
    'Select Year' => '',
    'Toggle Period' => '',
];
