<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clear selection' => 'Limpar seleção',
    'Close the picker' => 'Fechar',
    'Decrement Hour' => 'Decrementar Hora',
    'Decrement Minute' => 'Decrementar Minuto',
    'Decrement Second' => 'Decrementar Segundo',
    'Go to today' => 'Ir para Hoje',
    'Increment Hour' => 'Incrementar Hora',
    'Increment Minute' => 'Incrementar Minuto',
    'Increment Second' => 'Incrementar Segundo',
    'Next Century' => 'Próximo Céculo',
    'Next Decade' => 'Próxima Década',
    'Next Month' => 'Próximo Mês',
    'Next Year' => 'Próximo Ano',
    'Pick Hour' => 'Pegar Hora',
    'Pick Minute' => 'Pegar Minuto',
    'Pick Second' => 'Pegar Segundo',
    'Previous Century' => 'Céculo Anterior',
    'Previous Decade' => 'Próxima Década',
    'Previous Month' => 'Mês Anterior',
    'Previous Year' => 'Ano Anterior',
    'Select Decade' => 'Selecionar Década',
    'Select Month' => 'Selecionar Mês',
    'Select Time' => 'Selecionar Hora',
    'Select Year' => 'Selecionar Dia',
    'Toggle Period' => 'Trocar Período',
];
